Generate issue
BrunoLevy/learn-fpga pull request #36
Opened 2021-03-31 03:39 UTC by corerd

Hello Bruno,

First of all, many thanks for your great job.

I had issues generating the bitstream for IceStick ICE40HX1K that I fixed in the following way.

My devices configuration icestick_config.v file:

`define NRV_IO_LEDS          // Mapped IO, LEDs D1,D2,D3,D4 (D5 is used to display errors)
//`define NRV_IO_IRDA          // In IO_LEDS, support for the IRDA on the IceStick (WIP)
`define NRV_IO_UART          // Mapped IO, virtual UART (USB)
//`define NRV_IO_SSD1351       // Mapped IO, 128x128x64K OLED screen
//`define NRV_IO_MAX7219       // Mapped IO, 8x8 led matrix
`define NRV_MAPPED_SPI_FLASH // SPI flash mapped in address space. Use with MINIRV32 to run code from SPI flash.

I kept the remainder the same.

Toolchain:

Yosys 0.9
Icarus Verilog version 10.3 (stable)
Verilator 4.028 

Issue #1. ERROR: Identifier xxx is implicitly declared

To let the synthesis continue, I had to declare them in some way.
I state that I'm new in FPGA design and Verilog coding, then I'm not sure to had made the right things.
Particularly, in SSD1351_1331.v file.
But the synthesis completes and the bitstream works well (I don't use SSD1351 device).

Issue #2. Missing wait_cycles.S file

This file is required by the built process and I restored it from one of your previous commit.

Issue #3. sieve.c example

I added an infinite loop to see the output continuously.

Issue #4. NextPNR submodules sources

Indeed this is not an issue related to you.
Some submodule dependencies have been added to the NextPNR repository.
I suggest you to include this information in your toolchain install guide.

2021-03-31 06:46 UTC, BrunoLevy requested changes
Now femtorv32 on the IceStick has a cycle counter (gives a much cleaner way / precise way of measuring timings), and wait_cycles.S is replaced with wait_cycles.c, that uses the new cycles()
function (two different implementations in cycles_ice_stick.c for the IceStick and cycles.S for larger devices (that can have a 64-bits cycles counters). 
Normally the repository and Makefiles are uptodate and should work properly (maybe you checked out an intermediary state where I forgot to commit wait_cycles.c), would you retry ?

2021-03-31 06:48 UTC, BrunoLevy approved these changes
Thank you !

2021-03-31 07:19 UTC, BrunoLevy reviewed
Thank you for the explanation (variables in "generate" blocks are local), I did not know that (and my version of Yosys is maybe too permissive).
Your suggested fixes will make it compile, but will break other things for the operation of the small OLED screen, I'll try to find another solution.
UPDATE: Reading more about generate and variable scopes, I'll probably rewrite it using macros (not as elegant, but at least will be correct)

2021-03-31 07:20 UTC, BrunoLevy reviewed
I'd rather put a for(;;) than a goto :-)

2021-03-31 17:21 UTC, BrunoLevy commented
I think I have fixed the issue, please tell me what it gives with your version.
Best wishes,
-- Bruno

2021-03-31 18:33 UTC, corerd commented
Thank you, Bruno!
I just merged your upstream repository.
Did you forgot the wait_cycles.c file? :-)
Now both the bitstream and the firmware examples are compiled without errors.
Neither implicitly declared identifiers, nor missing functions errors are raised.

But....
Nothing is displayed anymore on the serial terminal :-(
I tried hello.prog and sysconfig.prog at baud rates: 115200, 57600, 28800, 19200, 9800.

2021-04-01 12:07 UTC, BrunoLevy commented
Thank you very much for your feedback ! 
And thank you for the explanation of the visibility of wires/regs in generate blocks (it was a mystery for me before)
(and yes, I'll follow your suggestion of deactivating the OLED screen and led matrix that not everybody has)
Best wishes,
-- Bruno

2021-04-01 12:07 UTC, closed without merging